# website::tag::1:: Build a simple Docker image that contains a text file with the contents "Hello, World!"
FROM ubuntu:18.04
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"
RUN echo 'Hello, World!' > /test.txt
